[view]
max_visible_pixels = 25000

[world]
width = 1000
height = 1000

[forest]
seed_prob = 0.05
iterations = 3
birth_threshold = 2

[water]
density = 0.001
turn_prob = 0.1
stop_prob = 0.005
height_influence = 5.0


[villager]
hunger_loss_per_tick = 1 # 每tick（每天）消耗1点饥饿度
ticks_to_starve = 10    # 100点饥饿度，每tick掉1点，所以10 ticks后饿死
reproduction_cooldown_ticks = 360 # 现在是360 ticks (360天)

[time]
ticks_per_day = 1       # <--- 核心改动：现在1个Tick就是1天
ticks_per_year = 365    # <--- 相应调整：一年现在是365个Ticks
