# 地图基础配置
[map]
width = 1000
height = 1000
max_visible_pixels = 25000

# 森林生成参数
[terrain.forest]
seed_prob = 0.05
iterations = 3
birth_threshold = 2

# 水系生成参数
[terrain.water]
density = 0.001      # 河流源头的密度
turn_prob = 0.1      # 河流转向的概率
stop_prob = 0.005    # 河流停止的概率
height_influence = 50.0  # 高度场影响因子：
                        # - 值越大，水流越倾向于遵循地形坡度
                        # - 值越小，水流路径越随机
                        # - 建议范围：10.0 ~ 100.0

# 服务器配置
[server]
host = "0.0.0.0"
port = 16151
debug = true
